### ISSUE TITLE
Instantiating DogLog instance with instance-local options

### ISSUE THREAD

**Issue by yabberyabber** [jonahsnider/doglog#29]
Many logging libraries support instantiating new logger instances with their own unique configuration. The pattern seems useful in the context of FRC where you your logging configuration to apply on a per-subsystem basis.

What would folks think about a PR that adds this support to doglog? From looking at the source it seems straightforward to implement while also preserving the existing API. I'm happy to submit the PR but I'd like to make sure this proposal vibes with the original authors first.

An example of the usage might look something like this:
```java

import dev.doglog.DogLog
import dev.doglog.DogLogOptions

// Maybe the arm subsystem has something funky going on so we will
// enable more logging on it than usual
DogLog armLogger = new DogLog(new DogLogOptions().withCaptureNT(true).withKeyPrefix("arm/"));
Arm armSubsystem = new Arm(armLogger);

DogLog intakeLogger = new DogLog(new DogLogOptions().withKeyPefix("intake/"));
Intake intakeSubsystem = new Intake(intakeLogger);
```

In this example, anything that the Arm subsystem logs with the passed-in `armLogger` will use the DogLogOptions that `armLogger` was constructed with. The intake subsystem has its own logger with its own config that is separate. Logging for entire subsystems can be turned off and on by just changing how that subsystem's logger was instantiated. Each logger instance would share a global singleton LogQueuer instance.

This example also makes up a `DogLogOptions.withKeyPrefix(prefix string)` method which would save some that prefix to the DogLogOptions type. https://github.com/jonahsnider/doglog/blob/4fe1e8a888e9ac49d407eab6753f6399965f2d3f/lib/src/main/java/dev/doglog/DogLog.java#L63-L64 the configured prefix would just get combined with the `key` argument here. That way a line of code like
```
new DogLog(new DogLogOptions().withKeyPrefix("left-wheel/")).log("velocity", 12)
```
Is effectively the same as this once it gets written
```
new DogLog(new DogLogOptions()).log("left-wheel/velocity", 12)
```
A common issue that we ran into in 2024 was students forgetting that NT is a global namespace and using keys like "left-motor-velocity" in multiple subsystems. Having a structured logger that scopes the entries to the instance seems like an intuitive pattern to avoid making this kind of mistake (and also to keep NetworkTables organized).

I'm happy to work with one of our students to create the PR if this proposal seems in line with the scope and desires of doglog. I understand that simplicity is a goal of this project and that this may add more complexity to the tool than the team is willing to support.

**Comment by jonahsnider** [comment]
So, I see where you're coming from on this suggestion but I'm not sure about adding this. My main concern is that enabling this functionality (specifically, having different options per logger) will make it (slightly) more complex to configure the main logger options, which hurts user experience a little.

Since some options only make sense to be defined globally, I think there would need to be some separate class (ex. `DogLogInstanceOptions` vs `DogLogGlobalOptions` or something):

| Option         | Global                          | Instance |
| -------------- | ------------------------------- | -------- |
| Queue capacity | ✅                              | ❌       |
| NT publish     | ✅                              | ✅       |
| NT capture     | ✅                              | ❌       |
| DS capture     | ✅                              | ❌       |
| Log extras     | ✅                              | ❌       |
| Key prefix     | ✅ (probably not useful though) | ✅       |

I'll play around with some possible implementations for this now and update here if it seems like it can be added without increasing complexity for people only using the global logger.

**Comment by jonahsnider** [comment]
Unfortunately this kinda sucks really bad to implement because all the existing logging code is written under the assumption that there's just the one `DogLogOptions` object. Trying to refactor that code is possible, but would introduce a lot of complexity/friction for me as a maintainer. Which, unfortunately, I don't really want to do for something that seems like not a super important feature.

However, just adding support for key prefixes is easier, since there doesn't have to be any kind of complicated config merging done from the `LogThread`.

I made a little `ChildLogger` class here that you can just paste into your project. This will give you a way to have a scoped logger for each subsystem, even if it doesn't give you the full level of configurability for child loggers.

<details>
<summary>`ChildLogger`</summary>

```java
// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package dev.doglog;

import edu.wpi.first.util.struct.StructSerializable;

/** A child logger that prefixes all logged keys with the provided key prefix. */
public class ChildLogger {
  private final String keyPrefix;

  public ChildLogger(String keyPrefix) {
    this.keyPrefix = keyPrefix + "/";
  }

  /** Log a boolean array. */
  public void log(String key, boolean[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a boolean. */
  public void log(String key, boolean value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a double array. */
  public void log(String key, double[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a double. */
  public void log(String key, double value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a float array. */
  public void log(String key, float[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a float. */
  public void log(String key, float value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log an int array. */
  public void log(String key, int[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a long array. */
  public void log(String key, long[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a long. */
  public void log(String key, long value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a string array. */
  public void log(String key, String[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log an enum array. Enums will be converted to strings with {@link Enum#name()}. */
  public void log(String key, Enum<?>[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a string. */
  public void log(String key, String value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log an enum. The enum will be converted to a string with {@link Enum#name()}. */
  public void log(String key, Enum<?> value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a struct array. */
  public <T extends StructSerializable> void log(String key, T[] value) {
    DogLog.log(keyPrefix + key, value);
  }

  /** Log a struct. */
  public <T extends StructSerializable> void log(String key, T value) {
    DogLog.log(keyPrefix + key, value);
  }
}
```

</details>

I hope this is sufficient to solve your use case. And thank you for the interest in DogLog!
